In [1]:
import numpy as np

In [2]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')

In [3]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [4]:
m[1,0]

5

In [5]:
m[1, :]

matrix([[5, 6, 7, 8]])

In [6]:
m[:, 2]

matrix([[3],
        [7],
        [5]])

In [7]:
m[1, 2:]

matrix([[7, 8]])

In [8]:
m[0:2,1]

matrix([[2],
        [6]])

In [9]:
m[0:2,1:3]

matrix([[2, 3],
        [6, 7]])

In [10]:
cols = [0, 1, 3]
m[:, cols]

matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])

In [11]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')

In [12]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [13]:
type(m)

numpy.matrix

In [14]:
m = np.array(m)
type(m)

numpy.ndarray

In [15]:
m.shape

(3, 4)

In [16]:
m.max()

9

In [17]:
np.max(m)

9

In [18]:
m.max(axis=1)

array([4, 8, 9])

In [19]:
m.max(axis=0)

array([9, 6, 7, 8])

In [20]:
m.mean()

4.833333333333333

In [21]:
m.mean(axis=1)

array([2.5, 6.5, 5.5])

In [22]:
m.sum()

58

In [23]:
m.sum(axis=0)

array([15,  9, 15, 19])

In [24]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])

In [25]:
less_then_5 = nums < 5

In [26]:
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [27]:
pos_a = letters == 'a'

In [28]:
pos_a

array([ True, False, False, False,  True, False, False])

In [29]:
nums[less_then_5]

array([1, 2, 3, 4])

In [30]:
mod_m = np.logical_and(m>=3, m<=7)

In [31]:
mod_m

array([[False, False,  True,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True]])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
ticket_number = 123042

In [90]:
tick = list(map(int, str(ticket_number)))
print(tick)
if sum(tick[0:2+1]) == sum(tick[3:5+1]):
    print("Yes")
else:
    print("No")

[1, 2, 3, 0, 4, 2]
Yes
